### ISSUE TITLE
Dropping of "Alternative Terms"

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/vocabulary#2]
By having alternative terms we invite miscommunication as other words may be used instead of what we want to describe and people wonder what we mean. I can see a section where we describe "distinctions" eg. "A horse is different from a cow in that it is faster, leaner and has no horns".

**Comment by dkastl** [comment]
Maybe there is some misunderstanding. The idea of alternatives is not that we want to allow allternatives. It was just to have a list of terms used by others for similar things. Maybe we can delete it later, but I find it helpful for finding and agreement which vocabulary to use in the end.

Example: in my opinion we should use the term "account", but @marcchataigner meant this makes him think of an online account and it might be confusing with accounts later to be secured by Consento. So basically everyone used a different term for  that component, and to have a list of "alternatives" might serve as some "brainstorming" on one side and to indicate that there others use different names for similar purposes. 

So while I would go with "account" I think it's good to discuss if there aren't better names for that. We could call it a "profile" or a "workspace" for instance.

**Comment by martinheidegger** [comment]
It is a good idea to keep information and history on to what other words we considered and why we prefer the current term. Maybe Using a "similar terms" section and add an argument to each why it is different is a good idea?

**Comment by dkastl** [comment]
"similar terms" sounds good.
