### ISSUE TITLE
Drop "Status" for a living document.

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/vocabulary#3]
Treating the vocabulary as a living document in stead of having "status" should work better. A living document insists that at the same time that all terms are "final" they also still may be changing in future.

**Comment by dkastl** [comment]
Well, the idea was if there is some agreement already or not.

**Comment by martinheidegger** [comment]
A living document is to me both agreement and yet subject to change. On the one hand "what is written here is decided" on the other hand "what is decided here can be questioned through issues and is subject to change through pull requests".
